import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://n1.sdlcdn.com/imgs/j/k/0/Think-Like-a-Monk-Paperback-SDL663528126-1-e271c.jpg",
    title: "Think Like a Monk",
    author: "Jay Shetty",
    price: "399",
    discountedPrice: "359",
    rating: "3.5",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    img: "https://n2.sdlcdn.com/imgs/h/3/n/Good-Vibes-Good-Life-How-SDL029669905-1-4c2b8.jpg",
    title: "Good Vibes, Good Life",
    author: "Vex King",
    price: "350",
    discountedPrice: "310",
    rating: "3",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    img: "https://n4.sdlcdn.com/imgs/b/u/m/Sapiens-A-Brief-History-of-SDL155750180-1-24963.jpg",
    title: "Sapiens A Brief History of Humankind",
    author: "Yuval Noah",
    price: "900",
    discountedPrice: "850",
    rating: "4",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    img: "https://n2.sdlcdn.com/imgs/a/5/g/Tuesdays-With-Morrie-An-Old-SDL465984746-1-19dd9.jpg",
    title: "Tuesdays With Morrie",
    author: "Mitch Albom",
    price: "700",
    discountedPrice: "450",
    rating: "2",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    img: "https://n3.sdlcdn.com/imgs/a/4/g/A-Thousand-Splendid-Suns-SDL657791117-1-8c612.jpg",
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    price: "1000",
    discountedPrice: "870",
    rating: "1",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    img: "https://n2.sdlcdn.com/imgs/a/4/6/The-Forty-Rules-Of-Love-SDL020244542-1-97930.jpg",
    title: "The Forty Rules Of Love",
    author: "Elif Shafak",
    price: "399",
    discountedPrice: "280",
    rating: "5",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    img: "https://n4.sdlcdn.com/imgs/h/q/r/THE-ALCHEMIST-SDL742618637-1-ec9d8.jpeg",
    title: "THE ALCHEMIST",
    author: "Paulo Coelho",
    price: "500",
    discountedPrice: "450",
    rating: "4.5",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    img: "https://n3.sdlcdn.com/imgs/i/6/s/The-Great-Gatsby-SDL769415203-1-cf03c.jpg",
    title: "The Great Gatsby",
    author: " Scott Fitzgerald",
    price: "695",
    discountedPrice: "600",
    rating: "2",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    img: "https://n1.sdlcdn.com/imgs/j/u/s/Harry-Potter-And-The-Goblet-SDL034826386-1-91696.jpg",
    title: "Harry Potter And The Goblet Of Fire",
    author: "J.K. ROWLING",
    price: "525",
    discountedPrice: "450",
    rating: "4",
    categoryName: "kids",
  },
  {
    _id: uuid(),
    img: "https://n2.sdlcdn.com/imgs/j/y/n/Little-Cinderella-Is-More-Than-SDL544969950-1-2571c.jpg",
    title: "Little Cinderella Is More Than A Princess",
    author: "Maimoonah Mammi",
    price: "425",
    discountedPrice: "300",
    rating: "3",
    categoryName: "kids",
  },
  {
    _id: uuid(),
    img: "https://n4.sdlcdn.com/imgs/h/u/a/Blooms-of-Joy-SDL755939714-1-cbbe8.jpg",
    title: "Blooms of Joy",
    author: "Eman AL Fires",
    price: "405",
    discountedPrice: "340",
    rating: "3",
    categoryName: "kids",
  },
  {
    _id: uuid(),
    img: "https://n1.sdlcdn.com/imgs/f/y/l/Eyes-Of-The-Cat-SDL203741075-1-25bdd.jpg",
    title: "Eyes Of The Cat",
    author: "Ruskin Bond",
    price: "778",
    discountedPrice: "699",
    rating: "1",
    categoryName: "kids",
  },
];
