const INITIAL_DATA = "INITIAL_DATA";
const INITIALIZE_CATEGORY = "INITIALIZE_CATEGORY";
const PRICE_CHANGE = "PRICE_CHANGE";
const CATEGORY_CHANGE = "CATEGORY_CHANGE";
const SORT_BY = "SORT_BY";
const HIGH_TO_LOW = "HIGH_TO_LOW";
const LOW_TO_HIGH = "LOW_TO_HIGH";
const RATING_CHANGE = "RATING_CHANGE";
const CLEAR_ALL = "CLEAR_ALL";
export {
  INITIAL_DATA,
  INITIALIZE_CATEGORY,
  PRICE_CHANGE,
  CATEGORY_CHANGE,
  SORT_BY,
  HIGH_TO_LOW,
  LOW_TO_HIGH,
  RATING_CHANGE,
  CLEAR_ALL,
};
